/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.yuki.phonefinder;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int alert_dialog_icon=0x7f020000;
        public static final int ic_menu_update=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int icon_help=0x7f020003;
        public static final int icon_large=0x7f020004;
    }
    public static final class id {
        public static final int ImageView01=0x7f050003;
        public static final int LinearLayout02=0x7f050005;
        public static final int TextView01=0x7f050004;
        public static final int button_change=0x7f050007;
        public static final int password_edit=0x7f050001;
        public static final int password_view=0x7f050000;
        public static final int screen=0x7f050002;
        public static final int textview_verify_code=0x7f050006;
    }
    public static final class layout {
        public static final int alert_dialog_text_entry=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int alert_dialog_cancel=0x7f040009;
        public static final int alert_dialog_ok=0x7f040008;
        public static final int alert_dialog_password=0x7f040007;
        public static final int alert_dialog_text_entry=0x7f040006;
        public static final int app_desc=0x7f040002;
        public static final int app_help=0x7f040003;
        public static final int app_name=0x7f040001;
        public static final int app_tip=0x7f040004;
        public static final int button_change=0x7f04000a;
        public static final int hello=0x7f040000;
        public static final int menu_info=0x7f04000b;
        public static final int menu_market=0x7f04000d;
        public static final int menu_share=0x7f04000c;
        public static final int notify_text=0x7f040005;
        public static final int share_subject=0x7f04000e;
    }
}
